
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user 
  template:
    metadata:
      labels:
        app: user 
    spec:
      containers:
      - name: user
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/user:3.0.2
        ports:
        - containerPort: 8080
        envFrom:                                # envFrom : to inject a configMap
          - configMapRef:
              name: user-cm

--- 
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080


--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 8080 

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data: 
  MONGO_URL: "mongodb://admin1:roboshop1@roboshop-dev.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  REDIS_HOST: "redis-dev.robot.internal"